# Please ensure this file is kept in sync with Dockerfile.okd
FROM registry.ci.openshift.org/ocp/4.19:base-rhel9 AS builder

WORKDIR /tmp

RUN which dnf
RUN bash -c 'which dnf'

RUN dnf install vim -y
