# Please ensure this file is kept in sync with Dockerfile.okd
FROM registry.ci.openshift.org/ocp/4.19:base-rhel9 AS builder

WORKDIR /tmp

RUN which dnf
RUN bash -c 'which dnf'
RUN echo $PATH | tr : '\n'

RUN timeout 10 dnf install vim -y

RUN false



COPY prepare-efi.sh /bin/
RUN prepare-efi.sh redhat



